=== cat-bro/galactic-radio-telescope/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://cpt.tamu.edu/grs",
  "type": "object",
  "properties": {
    "galaxy_instance": {
      "id": "https://cpt.tamu.edu/grs/galaxy_instance",
      "type": "string",
      "default": "",
      "title": "Galaxy instance ID",
      "description": "set internally"
    },
    "starttime": {
      "id": "https://cpt.tamu.edu/grs/starttime",
      "type": "string",
      "default": "",
      "description": "Job entry creation time",
      "title": "Job Start Time"
    },
    "handler": {
      "id": "https://cpt.tamu.edu/grs/handler",
      "type": "string",
      "default": "",
      "description": "handler name"
    },
    "runner": {
      "id": "https://cpt.tamu.edu/grs/runner",
      "type": "string",
      "default": "",
      "description": "job runner id"
    },
    "exit_code": {
      "id": "https://cpt.tamu.edu/grs/exit_code",
      "type": "integer",
      "default": "0",
      "title": "Exit Code",
      "description": "exit code of the underlying wrapper"
    },
    "state": {
      "id": "https://cpt.tamu.edu/grs/state",
      "type": "string",
      "default": "ok",
      "title": "Job state",
      "description": "running jobs should be ignored."
    },
    "tool_id": {
      "id": "https://cpt.tamu.edu/grs/tool_id",
      "type": "string",
      "default": "",
      "description": "Full tool id, e.g. toolshed.g2.bx.psu.edu/repos/nilesh/bcftools/bcftools_view/0.0.1",
      "title": "Tool ID"
    },
    "tool_version": {
      "id": "https://cpt.tamu.edu/grs/tool_version",
      "type": "string",
      "default": "",
      "title": "Tool Version"
    },
    "params": {
      "id": "https://cpt.tamu.edu/grs/params",
      "type": "object",
      "properties": {},
      "description": "dictionary of parameters given to the job",
      "title": "Job Pararmeter Dictionary"
    },
    "metrics": {
      "id": "https://cpt.tamu.edu/grs/metrics",
      "type": "object",
      "properties": {
      },
      "description": "Job metrics section from the metrics plugin"
    }
  },
  "required": [
    "galaxy_instance",
    "starttime",
    "handler",
    "runner",
    "exit_code",
    "state",
    "tool_id",
    "tool_version",
    "params",
    "metrics"
  ]
}

=== cat-bro/galactic-radio-telescope/sample-data/test.json
[
  {
    "galaxy_instance": "deadbeefcafe",
    "starttime": "2014-07-15 18:18:17.433394",
    "handler": "local",
    "runner": "handler1",
    "exit_code": 0,
    "state": "ok",
    "tool_id": "toolshed.g2.bx.psu.edu/repos/nilesh/bcftools/bcftools_view/0.0.1",
    "tool_version": "0.0.1",
    "params": {
      "A": "false",
      "c": "true",
      "b": "false",
      "e": "false",
      "D": {"seq_dictionary": "false", "__current_case__": 1},
      "G": "false",
      "F": "false",
      "i": {"__current_case__": 1, "alt_indel_snp_ratio": "false"},
      "chromInfo": "/home/galaxy/galaxy/tool-data/shared/ucsc/chrom/?.len",
      "dbkey": "?",
      "N": "false",
      "g": "true",
      "S": "false",
      "u": "false",
      "t": {"mutation_rate": "false", "__current_case__": 1},
      "v": "true",
      "input": 10534,
      "p": {"variant_filter": "false", "__current_case__": 1}
    },
    "metrics": {
        "core": {
            "start_epoch": 1405448301.0000000,
            "end_epoch": 1405448301.0000000,
            "galaxy_slots": 1,
            "runtime_seconds": 0.0000
        },
        "meminfo": {
            "swaptotal": 16765948.0000000,
            "memtotal": 16423156.0000000
        },
        "cpuinfo": {
            "processor_count": 8
        }
    }
  }
]
